### ISSUE TITLE
Running tests against usegalaxy.org.au

### ISSUE THREAD

**Issue by cat-bro** [usegalaxy-eu/workflow-testing#51]
Could we please have these tests run for Galaxy Australia (usegalaxy.org.au)?

**Comment by hexylena** [comment]
Yeah, course! Just email an API key for an unprivileged account to @bgruening or [myself](mailto:hxr@hx42.org) and we'll add y'all.

**Comment by bgruening** [comment]
@cat-bro that would be great, yes we can do this! 

For EU we create a bot account (bot@usegalaxy.eu) and an API key. I would need both from you, so we can schedule those jobs.

**Comment by bgruening** [comment]
upps, too late :)

**Comment by bgruening** [comment]
@cat-bro I have sent you a mail and have setup the testing. You might want to add those fancy buttons to the readme as soon as we get some more green.
